CREATE TABLE public.tailors (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    name VARCHAR (255) NOT NULL,
    address VARCHAR(400),
    email VARCHAR(100) NOT NULL
);

CREATE TABLE public.users (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL,  
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    name VARCHAR(255) NOT NULL,
    phone VARCHAR(30) NOT NULL,
    username VARCHAR(50) UNIQUE NOT NULL,
    address VARCHAR(400),
    email VARCHAR(100) NOT NULL,
    password VARCHAR(255) NOT NULL,
    role INTEGER NOT NULL,
    tailor_id INTEGER DEFAULT 0 REFERENCES tailors ON UPDATE CASCADE ON DELETE SET DEFAULT
);

CREATE TABLE public.orders (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    user_id INTEGER NOT NULL REFERENCES users ON UPDATE CASCADE ON DELETE RESTRICT,
    tailor_id INTEGER NOT NULL REFERENCES tailors ON UPDATE CASCADE ON DELETE RESTRICT,
    status INTEGER NOT NULL,
    specification jsonb,
    price REAL NOT NULL
);

CREATE TABLE public.user_tokens (
    uuid VARCHAR(50) NOT NULL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    user_id INTEGER NOT NULL REFERENCES users ON UPDATE CASCADE ON DELETE CASCADE,
    expired_at TIMESTAMPTZ NOT NULL
);

CREATE TABLE public.materials (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    name VARCHAR(50) NOT NULL,
    color VARCHAR(50) NOT NULL,
    detail VARCHAR(400)
);

CREATE TABLE public.models (
    id SERIAL PRIMARY KEY,
    uuid VARCHAR(50) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    name VARCHAR(255) NOT NULL,
    detail VARCHAR(400)
);

CREATE TABLE public.tailor_models (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    tailor_id INTEGER NOT NULL REFERENCES tailors ON UPDATE CASCADE ON DELETE CASCADE,
    model_id INTEGER NOT NULL REFERENCES models ON UPDATE CASCADE ON DELETE RESTRICT,
    price REAL NOT NULL, 
);

CREATE TABLE public.tailor_materials (
    id SERIAL PRIMARY KEY,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    tailor_id INTEGER NOT NULL REFERENCES tailors ON UPDATE CASCADE ON DELETE CASCADE,
    material_id INTEGER NOT NULL REFERENCES models ON UPDATE CASCADE ON DELETE RESTRICT,
    price REAL NOT NULL, 
);

ALTER TABLE public.users
DROP COLUMN address;

ALTER TABLE public.tailors
ALTER COLUMN name DROP NOT NULL
ADD COLUMN phone VARCHAR(30) DEFAULT '' NOT NULL;

ALTER TABLE public.orders
ADD COLUMN user_address VARCHAR(255);
